### ISSUE TITLE
--yso error flag

### ISSUE THREAD

**Issue by dewest91** [qtc-de/remote-method-guesser#32]
Hello!

I was attempting to use the ysoserial jar file for attempting a filter-bypass scan, but the output shows that --yso is not a recognized flag:

└─$ java -jar rmg-4.3.0-jar-with-dependencies.jar enum 192.168.202.168 8686 --scan-action filter-bypass --yso ysososerial-master-8eb5cbfbf6-1.jar
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
usage: remote-method-guesser enum [-h] [--config path] [--verbose] [--no-color] [--stack-trace] [--bound-name name] [--follow] [--ssl] [--gopher] [--ssrf] [--ssrf-response hex] [--encode] [--raw] [--stream-protocol]
                             [--localhost-bypass] [--scan-action action [action ...]] [--activate] [--force-activation] [--dgc-method method] [--registry-method method] host port
remote-method-guesser: error: unrecognized arguments: '--yso'

Did you mean:
        --ssl

Is there a work around to use the ysoserial jar with that scan attempt?

**Comment by qtc-de** [comment]
Hi dewest91 :wave: 

the `enum` action does not require *ysoserial*. The `filter-bypass` action uses a gadget discovered by [An Trinh](https://twitter.com/_tint0) which is more recent than the bypass gadgets available in *ysoserial*. Just run the `enum` action without the `--yso` option and it should work fine.

If this works for your, please close the issue :slightly_smiling_face: 

Best
Tobias

**Comment by qtc-de** [comment]
Closed because of inactivity. Feel free to reopen, if the issue still exists.
