### ISSUE TITLE
Can't build the plugin

### ISSUE THREAD

**Issue by yesiamdollar** [qtc-de/remote-method-guesser#33]
Hello,

I was trying to build the plugin, but the output shows some errors:

command : bash plugins/build.sh target/rmg-4.3.0-jar-with-dependencies.jar plugins/GenericPrint.java GenericPrint.jar

output
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
plugins/GenericPrint.java:118: error: RemoteObjectWrapper is abstract; cannot be instantiated
            RemoteObjectWrapper liveRef = new RemoteObjectWrapper(o);
                                          ^
plugins/GenericPrint.java:126: error: cannot find symbol
            if(liveRef.csf != null)
                      ^
  symbol:   variable csf
  location: variable liveRef of type RemoteObjectWrapper
plugins/GenericPrint.java:127: error: cannot find symbol
                csf = liveRef.csf.getClass().getName();
                             ^
  symbol:   variable csf
  location: variable liveRef of type RemoteObjectWrapper
plugins/GenericPrint.java:129: error: cannot find symbol
            if(liveRef.ssf != null)
                      ^
  symbol:   variable ssf
  location: variable liveRef of type RemoteObjectWrapper
plugins/GenericPrint.java:130: error: cannot find symbol
                ssf = liveRef.ssf.getClass().getName();
                             ^
  symbol:   variable ssf
  location: variable liveRef of type RemoteObjectWrapper
plugins/GenericPrint.java:133: error: cannot find symbol
            Logger.printlnMixedBlue("Endpoint:\t\t", liveRef.getTarget());
                                                            ^
  symbol:   method getTarget()
  location: variable liveRef of type RemoteObjectWrapper
plugins/GenericPrint.java:134: error: cannot find symbol
            Logger.printlnMixedBlue("ObjID:\t\t\t", liveRef.objID.toString());
                                                           ^
  symbol:   variable objID
  location: variable liveRef of type RemoteObjectWrapper
7 errors

------------------------------------------------------------------------------------------------

I'm not a javatar, so I found it hard to fix

**Comment by qtc-de** [comment]
Hi @yesiamdollar :wave: 

thanks for reporting. Issue should now been fixed on master :slightly_smiling_face: 

Best
Tobias

**Comment by yesiamdollar** [comment]
all good, thank you ✅
