### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by G0uZ1** [qtc-de/remote-method-guesser#38]
Hello Tobias，
This is a great tool, but the security risks of batch testing Java-RMI services are required in daily work. Hope to add batch testing function later，Thanks~

： ）

**Comment by qtc-de** [comment]
Hi @G0uZ1 :wave: 

thanks for the feedback. If I understand you correctly you want some function like reading hosts from a file and testing them all together. Sounds like a great feature request to me :+1:

The actual challenge here is probably the output format. Running `rmg` on several hosts in sequence can obviously done using e.g. a *for loop* in bash. However, when running *rmg* agains 50+ hosts, going through the output is a tedious work... 

I will think about an appropriate output format and implement it once I have an reasonable idea. Quite busy lately, so don't expect the changes to soon, but they will come :wink:
